name: native_image_picker_macos
description: "A macOS platform implementation of image_picker using the native system picker instead of file_selector"
version: 0.0.2
repository: https://github.com/CompileKernel/native-image-picker-macos
documentation: https://github.com/CompileKernel/native-image-picker-macos
homepage: https://github.com/CompileKernel/native-image-picker-macos
issue_tracker: https://github.com/CompileKernel/native-image-picker-macos/issues
topics: [image-picker, files, file-selection]

environment:
  sdk: ^3.3.0
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker_platform_interface: ^2.11.0
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  pigeon: ^26.0.1
  build_runner: ^2.9.0

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: NativeImagePickerPlugin
